### ISSUE TITLE
Unable to stop/terminate the sandalone server.

### ISSUE THREAD

**Issue by jails** [peridot-php/webdriver-manager#11]
When starting the manager through:

``` php
$manager = new Manager();
$manager->startInBackground();
```

two processes are created:

```
17:38   0:00 sh -c java -jar /home/jaillet/peridot-php/webdriver-manager/binaries/selenium-server-standalone
17:38   0:01 java -jar /home/jaillet//peridot-php/webdriver-manager/binaries/selenium-server-standalone-2.46.
```

However when calling `->close()` on the manager, only the parent process is terminated and the sandalone server is still running:

```
17:38   0:01 java -jar /home/jaillet//peridot-php/webdriver-manager/binaries/selenium-server-standalone-2.46.
```

I think it's probably related to https://bugs.php.net/bug.php?id=39992

**Comment by brianium** [comment]
Interesting... I have never noticed it. According to the bottom of that thread, it is not a problem on OS X (where I do most of my testing). The poster mentions a possible work around involving writing pids out for use later. I will try to investigate. If you come up with a solution in the meantime, I would certainly appreciate a PR :)

Thanks for opening the issue.

**Comment by jails** [comment]
Fixed in https://github.com/peridot-php/webdriver-manager/pull/14
